fix(action): dynamic max-parallel

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -73,7 +73,7 @@ jobs:
       - name: Decide Idle Github Action Self-Hosted Runner Number
         id: detect
         env:
-          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          GH_TOKEN: ${{ secrets.ACTIONS_MANAGER_TOKEN }}
         run: |
           ORGS=${{ github.repository_owner }}
           REPO=${{ github.event.repository.name }}
@@ -84,14 +84,29 @@ jobs:
           RESP_REPO=$(curl -s -H "Authorization: token $GH_TOKEN" \
             https://api.github.com/repos/${OWNER}/${REPO}/actions/runners)
 
-          # Parse number of idle runners (online)
-          IDLE_ORGS=$(echo "$RESP_ORGS" | jq '[.runners[] | select(.status == "online")] | length' || echo 0)
-          IDLE_REPO=$(echo "$RESP_REPO" | jq '[.runners[] | select(.status == "online")] | length' || echo 0)
+          RESP_ORGS_SUCCESS=$(echo "$RESP_ORGS" | jq -r '.message // empty')
+          RESP_REPO_SUCCESS=$(echo "$RESP_REPO" | jq -r '.message // empty')
 
-          echo "| Org idle runners: $IDLE_ORGS"
-          echo "| Repo idle runners: $IDLE_REPO"
-          echo "| Total idle runners: $((IDLE_ORGS + IDLE_REPO))"
-          echo "idle=$((IDLE_ORGS + IDLE_REPO))" >> "$GITHUB_OUTPUT"
+          if [ -n "$RESP_ORGS_SUCCESS" ] || [ -n "$RESP_REPO_SUCCESS" ]; then
+              echo "| Error fetching repository runners: $RESP_REPO"
+              echo "| Error fetching organization runners: $RESP_ORGS"
+              IDLE_ORGS=0
+              IDLE_REPO=0
+          else
+              echo "| Successfully fetched runners for organization and repository."
+              # Parse number of idle runners (online)
+              IDLE_ORGS=$(echo "$RESP_ORGS" | jq '[.runners[] | select(.status == "online")] | length' || echo 0)
+              IDLE_REPO=$(echo "$RESP_REPO" | jq '[.runners[] | select(.status == "online")] | length' || echo 0)
+          fi
+
+          echo "| Detected idle runners in org: $IDLE_ORGS"
+          echo "| Detected idle runners in repo: $IDLE_REPO"
+          TOTAL_IDLE=$((IDLE_ORGS + IDLE_REPO))
+          echo "| Detected idle runners total: $TOTAL_IDLE"
+          DECIDE=$((TOTAL_IDLE > 0 ? TOTAL_IDLE : 2))
+          echo "| Decision: $DECIDE"
+
+          echo "idle=$DECIDE" >> "$GITHUB_OUTPUT"
 
   test_py:
     name: Test
@@ -104,7 +119,7 @@ jobs:
         qiskit-version: [v1, v2]
         python-version: ["3.13", "3.9", "3.12", "3.11", "3.10"]
       fail-fast: false
-      max-parallel: ${{ needs.check_version.outputs.idle || 2 }}
+      max-parallel: ${{ needs.check_version.outputs.idle }}
 
     steps:
       - uses: actions/checkout@v4
